window.integrationDefaultLangData={
     "button.cancel":"Cancel",
            "button.connect":"Connect to Zoom",
            "button.startMeeting":"Start meeting",
            "button.copy": "Copy",
            "button.create":"Create",
            "button.scheduleMeeting":"Schedule meeting",
            "meeting.url": "Meeting URL",
            "meeting.date":"Meeting date",
            "meeting.topic":"Meeting topic",
            "meeting.timezone": "Timezone",
            "meeting.time":"Meeting time",
            "meeting.duration": "Duration",
            "servicedesk.error.topic":"Please input the meeting topic",
            "servicedesk.error.topic.length":"The length of the meeting topic must be less than 200",
            "servicedesk.error.meetingDate":"Please select meeting date and time",
            "servicedesk.error.meetingDate.format":"Please check date and time format",
            "servicedesk.error.comment":"",
            "servicedesk.error.emptyBody": "You are trying to post empty body.",
            "servicedesk.error.checkInput": "Please check your input",
            "servicedesk.error.unknown": "An error has occurred.",
            "servicedesk.label.timezone":"Select the meeting timezone",
            "servicedesk.label.duration":"Select the meeting duration",
            "servicedesk.label.comment":"Input your comment here",
            "servicedesk.label.schedule":"Schedule a meeting",
            "servicedesk.label.recording": "Record meeting",
            "servicedesk.label.comment.txt": "Comment"
}