window.timezoneCity={
"Pacific/Midway":"Midway Island, Samoa",
"Pacific/Pago_Pago":"Pago Pago",
"Pacific/Honolulu":"Hawaii",
"America/Anchorage":"Alaska",
"America/Vancouver":"Vancouver",
"America/Los_Angeles":"Pacific Time (US and Canada)",
"America/Tijuana":"Tijuana",
"America/Denver":"Mountain Time (US and Canada)",
"America/Edmonton":"Edmonton",
"America/Phoenix":"Arizona",
"America/Mazatlan":"Mazatlan",
"America/Chicago":"Central Time (US and Canada)",
"America/Winnipeg":"Winnipeg",
"America/Regina":"Saskatchewan",
"America/Mexico_City":"Mexico City",
"America/Guatemala":"Guatemala",
"America/El_Salvador":"El Salvador",
"America/Managua":"Managua",
"America/Costa_Rica":"Costa Rica",
"America/New_York":"Eastern Time (US and Canada)",
"America/Montreal":"Montreal",
"America/Indianapolis":"Indiana (East)",
"America/Panama":"Panama",
"America/Bogota":"Bogota",
"America/Lima":"Lima",
"America/Halifax":"Halifax",
"America/Puerto_Rico":"Puerto Rico",
"America/Caracas":"Caracas",
"America/Santiago":"Santiago",
"America/St_Johns":"Newfoundland and Labrador",
"America/Montevideo":"Montevideo",
"America/Araguaina":"Brasilia",
"America/Argentina/Buenos_Aires":"Buenos Aires, Georgetown",
"America/Godthab":"Greenland",
"America/Sao_Paulo":"Sao Paulo",
"Atlantic/Azores":"Azores",
"Canada/Atlantic":"Atlantic Time (Canada)",
"Atlantic/Cape_Verde":"Cape Verde Islands",
"UTC":"Universal Time UTC",
"Etc/Greenwich":"Greenwich Mean Time",
"Europe/Belgrade":"Belgrade, Bratislava, Ljubljana",
"CET":"Sarajevo, Skopje, Zagreb",
"Atlantic/Reykjavik":"Reykjavik",
"Europe/Dublin":"Dublin",
"Europe/London":"London",
"Europe/Lisbon":"Lisbon",
"Africa/Casablanca":"Casablanca",
"Africa/Nouakchott":"Nouakchott",
"Europe/Oslo":"Oslo",
"Europe/Stockholm":"Stockholm",
"Europe/Copenhagen":"Copenhagen",
"Europe/Berlin":"Amsterdam, Berlin, Rome, Stockholm, Vienna",
"Europe/Helsinki":"Helsinki",
"Europe/Amsterdam":"Amsterdam",
"Europe/Brussels":"Brussels",
"Europe/Luxembourg":"Luxembourg",
"Europe/Paris":"Paris",
"Europe/Zurich":"Zurich",
"Europe/Madrid":"Madrid",
"Europe/Rome":"Rome",
"Europe/Warsaw":"Warsaw",
"Europe/Prague":"Prague Bratislava",
"Europe/Vienna":"Vienna",
"Europe/Budapest":"Budapest",
"Europe/Sofia":"Sofia",
"Europe/Moscow":"Moscow",
"Europe/Istanbul":"Istanbul",
"Europe/Athens":"Athens",
"Europe/Bucharest":"Bucharest",
"Africa/Bangui":"West Central Africa",
"Africa/Algiers":"Algiers",
"Africa/Tunis":"Tunis",
"Africa/Harare":"Harare, Pretoria",
"Africa/Nairobi":"Nairobi",
"Asia/Nicosia":"Nicosia",
"Asia/Beirut":"Beirut",
"Asia/Damascus":"Damascus",
"Asia/Jerusalem":"Jerusalem",
"Asia/Amman":"Amman",
"Africa/Tripoli":"Tripoli",
"Africa/Cairo":"Cairo",
"Africa/Johannesburg":"Johannesburg",
"Asia/Baghdad":"Baghdad",
"Asia/Kuwait":"Kuwait",
"Asia/Riyadh":"Riyadh",
"Asia/Bahrain":"Bahrain",
"Asia/Qatar":"Qatar",
"Asia/Aden":"Aden",
"Asia/Tehran":"Tehran",
"Africa/Khartoum":"Khartoum",
"Africa/Djibouti":"Djibouti",
"Africa/Mogadishu":"Mogadishu",
"Asia/Dubai":"Dubai",
"Asia/Muscat":"Muscat",
"Asia/Baku":"Baku, Tbilisi, Yerevan",
"Asia/Kabul":"Kabul",
"Asia/Yekaterinburg":"Yekaterinburg",
"Asia/Tashkent":"Islamabad, Karachi, Tashkent",
"Asia/Calcutta":"India",
"Asia/Kathmandu":"Kathmandu",
"Asia/Novosibirsk":"Novosibirsk",
"Asia/Rangoon":"Rangoon",
"Asia/Almaty":"Almaty",
"Asia/Dacca":"Dacca",
"Asia/Bangkok":"Bangkok",
"Asia/Krasnoyarsk":"Krasnoyarsk",
"Asia/Dhaka":"Astana, Dhaka",
"Asia/Saigon":"Vietnam",
"Asia/Jakarta":"Jakarta",
"Asia/Shanghai":"Beijing, Shanghai",
"Asia/Irkutsk":"Irkutsk, Ulaanbaatar",
"Asia/Hong_Kong":"Hong Kong",
"Asia/Taipei":"Taipei",
"Asia/Kuala_Lumpur":"Kuala Lumpur",
"Asia/Singapore":"Singapore",
"Australia/Perth":"Perth",
"Asia/Tokyo":"Osaka, Sapporo, Tokyo",
"Asia/Yakutsk":"Yakutsk",
"Asia/Seoul":"Seoul",
"Australia/Darwin":"Darwin",
"Australia/Adelaide":"Adelaide",
"Pacific/Port_Moresby":"Guam, Port Moresby",
"Asia/Vladivostok":"Vladivostok",
"Australia/Brisbane":"Brisbane",
"Australia/Sydney":"Canberra, Melbourne, Sydney",
"Australia/Hobart":"Hobart",
"Asia/Magadan":"Magadan",
"SST":"Solomon Islands",
"Pacific/Noumea":"New Caledonia",
"Asia/Kamchatka":"Kamchatka",
"Pacific/Fiji":"Fiji Islands, Marshall Islands",
"Pacific/Auckland":"Auckland, Wellington",
"Asia/Kolkata":"Mumbai, Kolkata, New Delhi",
"Europe/Kiev":"Kiev",
"America/Tegucigalpa":"Tegucigalpa",
"Pacific/Apia":"Independent State of Samoa",
"Europe/Minsk":"Minsk",
"America/Juneau":"Juneau",
"America/Chihuahua":"Chihuahua",
"America/Monterrey":"Monterrey",
"America/La_Paz":"La Paz",
"America/Guyana":"Guyana"};
